### ISSUE TITLE
Failure to write to temp directory in Windows

### ISSUE THREAD

**Issue by opoudjis** [metanorma/html2doc#51] opened 2020-12-15 11:17 UTC
The line 

https://github.com/metanorma/html2doc/blob/d60bd67ef12c08e48158ccfd673046fa0b6250d1/lib/html2doc/mime.rb#L99

````
      FileUtils.cp local_filename, File.join(dir, new_filename)
````

is failing in Windows when run from a subdirectory of User/Desktop (c:/users/PC/Desktop/Naming/csd-name-models/sources), with a read error on the destination file: Errno::EACCES: Permission denied @rb_sysopen 

Same error if new_filename is shorter. Same error if local_filename is shorter. Error goes away if dir is outside of the user Desktop, including dir = c:/users/PC, and dir = f:/naming

There is clearly something off about running Metanorma on subdirectories of Desktop

**Comment by manuel489** [comment] 2020-12-16 00:42
I can't replicate this issue on my side.

I tried compiling the adoc file directly on Desktop folder and within a subdirectory of Desktop folder. I could generate the document (html and doc) in both cases.

**Comment by CAMOBAP** [comment] 2020-12-16 05:48
@manuel489 could you please show security tab for this folder (as described here https://exchangepedia.com/2017/11/get-file-or-folder-permissions-using-powershell.html)

**Comment by manuel489** [comment] 2020-12-16 06:06
Sure @CAMOBAP, here you are:

![image](https://user-images.githubusercontent.com/33627611/102311386-2a4d4d80-3f43-11eb-966f-c0220bc73d7f.png)

And from Powershell (as described in the link you shared):
`````
PS C:\Users\Manuel> (get-acl .\Desktop\).access | ft IdentityReference,FileSystemRights,AccessControlType,IsInherited,InheritanceFlags -auto

IdentityReference      FileSystemRights AccessControlType IsInherited                InheritanceFlags
-----------------      ---------------- ----------------- -----------                ----------------
NT AUTHORITY\SYSTEM         FullControl             Allow       False ContainerInherit, ObjectInherit
BUILTIN\Administrators      FullControl             Allow       False ContainerInherit, ObjectInherit
LAPTOP-NCDSEH46\Manuel      FullControl             Allow       False ContainerInherit, ObjectInherit
NT AUTHORITY\SYSTEM         FullControl             Allow        True ContainerInherit, ObjectInherit
BUILTIN\Administrators      FullControl             Allow        True ContainerInherit, ObjectInherit
LAPTOP-NCDSEH46\Manuel      FullControl             Allow        True ContainerInherit, ObjectInherit
`````

**Comment by CAMOBAP** [comment] 2021-11-07 17:22
@manuel489 if this is still actual, please open PowerShell and execute: `(Get-Acl -Path c:\users\PC\Desktop).Access` to check if any folder has non FullControll access

**Comment by CAMOBAP** [comment] 2021-11-18 18:19
Closing this issue because impossible to reproduce

**Closed by CAMOBAP** 2021-11-18 18:19 UTC
